[platformio]
default_envs = nanorp2040connect

[env:nanorp2040connect]
platform = platformio/raspberrypi@1.20.0
board = nanorp2040connect
framework = arduino
platform_packages =
    platformio/framework-arduino-mbed@4.6.0
    platformio/toolchain-gccarmnoneeabi@1.90201.191206
    platformio/tool-rp2040tools@1.0.2
lib_deps =
    arduino-libraries/Arduino_LSM6DSOX@1.1.2
    mikalhart/TinyGPSPlus@1.1.0
    arduino-libraries/SD@1.3.0
monitor_speed = 115200

[env:native]
platform = platformio/native@1.2.1
test_framework = unity
test_filter = test_core
test_build_src = no
build_unflags = -std=gnu++11
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Wpedantic
    -Werror
